### ISSUE TITLE
Same functionality as rewrite branch of Docile.jl?

### ISSUE THREAD

**Issue by thofma** [MichaelHatherly/Lapidary.jl#18]
I am currently using the rewrite branch of Docile.jl for documentation generation of [Hecke](https://github.com/thofma/Hecke.jl) and I am very happy with it (thanks). Will Lapidary.jl have the same functionality (or maybe it does already)? In particular I make heavy use of the ability to "dispatch" doc strings. I never dump all docstrings associated to a function at one place of the documentation. Instead I use `@(function1(::argument1))` at one place and `@(function1(::argument2))` at another place. Will this feature be available in Lapidary?

**Comment by MichaelHatherly** [comment]
> Will Lapidary.jl have the same functionality

Yes. That's the plan. Most basic parts are already done, though will need some polish before general release once I've got some time.

> I never dump all docstrings associated to a function at one place of the documentation. Instead I use `@(function1(::argument1))` at one place and `@(function1(::argument2))` at another place. Will this feature be available in Lapidary?

Yes, you should be able to get the same result using something like

```markdown
...

    {docs}
    function1(::argument1)

...

    {docs}
    function1(::argument2)

...
```

`{docs}` blocks can contain more than one function/type, so you can do

```markdown
...

    {docs}
    function1(::argument1)
    function1(::argument2)

...
```

to avoid having dozens of `{docs}` blocks.

Also, `@module{Hecke}` syntax is replaced by

```markdown
...

    {meta}
    CurrentModule = Hecke

...
```

Doesn't look as though Hecke uses any other features currently, so that should cover everything. If there's anything else unclear in the readme just give me a shout.

**Comment by thofma** [comment]
Awesome! Thanks a lot!
