### ISSUE TITLE
Support for Julia 0.4

### ISSUE THREAD

**Issue by abhijithch** [MichaelHatherly/Lapidary.jl#19]
`using Lapidary` throws an error `UndefVarError: Footnote not defined`.

**Comment by MichaelHatherly** [comment]
`Footnote` is only available in recent Julia 0.5 builds, so the package doesn't really support 0.4 as the REQUIRE file implies. I'll push a fix bumping the version shortly.

**Comment by MichaelHatherly** [comment]
Fixed in 1ab667b4f10ccc6f557edcb3aff5897a2b71eda4. Support for 0.4 might be possible with some Compat.jl fixes and conditional definitions, which I may have time to look into during this month hopefully. If you're tied to 0.4 and need this working soon then patches are very much welcome.

I'll leave this open as a tracker for possible 0.4 support.

**Comment by abhijithch** [comment]
cc @mdpradeep

**Comment by MichaelHatherly** [comment]
Should be fixed by 5ca772d60be0eaab89c9e9b3257c4a2811d17199. Do re-open if you run into troubles on 0.4 with this.
