### ISSUE TITLE
Deploy on master branch commits

### ISSUE THREAD

**Issue by tshort** [MichaelHatherly/Lapidary.jl#21]
Awesome package!

As a test, I converted part of the DataFrames documentation:

https://tshort.github.io/DataFrames.jl/

Many packages use master as the development branch. So with the way `deploydocs` works, the documentation is for the development branch. It'd be better to have the documentation point to the latest package release. Here are some options to cover this case:

* Use a real "devel" branch, and only use master for releases. This works now.

* Have an option to specify a branch other than master for building, "releases" for example. 

* Have `deploydocs` only build if it's a tagged version.

Better ideas?

One downside to gh-pages is that there's only one branch. You can't have documentation for different releases or for the development version. It'd be nice to have a way around that. Maybe `deploydocs` could write to a different repo (DataFrames.jl-devdocs) for development commits.

**Comment by MichaelHatherly** [comment]
Thanks for trying it out. Those DataFrames docs look great.

I figured we'd need to handle versioned docs soon. Perhaps the following would work without needing multiple doc branches:

Store generated docs in sub-directories of the gh-pages branch. So we'd have directories `latest`, `stable`, and `v0.0.1`, etc.

On every commit to `master` `deploydocs` would update `latest`. When a tagged commit is pushed then `latest` and `stable` are both updated with the same content and a `v...` directory is also created with that content. Older `v...` directories could be manually removed by the repo owner if the branch starts getting quite big.

Given that travis has access, https://docs.travis-ci.com/user/environment-variables/,  to the tag, `TRAVIS_TAG`, I think this could be a workable approach. Package authors could then link to their `latest` and `stable` sub-directories instead of the root dir.

Might also be worth exposing a keyword for choosing which branch/branches to trigger build on, though that may be unnecessary if what I've outlined above works. You should, I think, be able to push to a different repo by changing the `repo` keyword to something else, though I've not actually tried that yet.

**Comment by tshort** [comment]
Great plan, @MichaelHatherly!

**Comment by MichaelHatherly** [comment]
As far as I can tell 9326f0d11ed3c46b35a32f328e2ab63ecd295b94, which adds this feature, appears to work. When commits are made to the `master` branch, or whatever the keyword `latest` is set to, the `latest` directory is updated. When tags are pushed then `stable` is updated and a new directory named after the tag is created.

(Probably best to empty out your `gh-pages` branch prior to trying this.)

**Comment by tshort** [comment]
That was fast! Thanks!

**Comment by tshort** [comment]
Works great!

https://tshort.github.io/DataFrames.jl/latest
https://tshort.github.io/DataFrames.jl/stable
https://tshort.github.io/DataFrames.jl/v0.6.11

One minor enhancement request is to stick the version number somewhere on the left side. The material theme supports a version. I'm not sure what it does with it.

    extra:
      version: '0.1.0'

**Comment by MichaelHatherly** [comment]
The `version` setting should display on the left next to the package name. Something like

![2016-03-14-084947_4966x1080_scrot](https://cloud.githubusercontent.com/assets/6144086/13736956/f534cff0-e9c1-11e5-9a7a-f33f90f00907.png)
